### ISSUE TITLE
Include MacOS in Travis-CI build matrix

### ISSUE THREAD

**Issue by JakobGM** [JakobGM/astrality#11]
As I mainly develop on a linux machine, Travis-CI should be used to ensure that everything works on MacOS. I had a weird ``time.sleep`` bug on MacOS in an earlier version of Astrality when using too large values, while it worked perfectly on Linux.

Travis-CI supports [osx](https://docs.travis-ci.com/user/multi-os/) build environments, but [lacking python support](https://github.com/travis-ci/travis-ci/issues/2312) needs to be hacked around. [NeoVim](https://github.com/neovim/neovim) has managed this by specifying a [pre_install script](https://github.com/neovim/neovim/blob/master/ci/before_install.sh), which we could adapt to our own needs.

**Comment by sshashank124** [comment]
I don't have an Apple machine either so I don't know how much I can help with this

**Comment by JakobGM** [comment]
You wouldn't really have to have an Apple machine to do it, as you would push a seperate branch to remote, where you edit the ``.travis.yml`` file. Then you see how Travis responds to the change when it tries to run the MacOS build matrix.
