### ISSUE TITLE
Created directories are not cleaned up

### ISSUE THREAD

**Issue by KeithScheiwiller** [JakobGM/astrality#139]
(This kinda got lost on #137 so I thought I'd just make it an issue, hope that's ok.)

Both the copy and symlink actions do not include bookkeeping for directories they create in order to deploy dotfiles. This means that on cleanup, you are left with empty directories. I can provide a repro if needed.

Ideally these directories should be handled by the persistence module, and properly cleaned up as files are (see my code on #137). Otherwise this behavior should be documented as not supported.

**Comment by JakobGM** [comment]
> This kinda got lost on #137 so I thought I'd just make it an issue, hope that's ok.

All good, I like it that way! :+1: 

> Both the copy and symlink actions do not include bookkeeping for directories they create in order to deploy dotfiles. This means that on cleanup, you are left with empty directories. I can provide a repro if needed.
> Ideally these directories should be handled by the persistence module, and properly cleaned up as files are (see my code on #137). Otherwise this behavior should be documented as not supported.

I definitely think that this should be supported. As you have mentioned already, we could add a `MKDIR` creation method [here](https://github.com/jakobgm/astrality/blob/c8968cb1b1ef4678887545b9cfc71531db29c795/astrality/persistence.py#L16) in the `persistence` module and clean up accordingly.

But there are some design decisions to be made first:

1. What to do if a created directory has been populated by new files *not* created by astrality (or not the same module at least). Should the directory still be deleted at cleanup?
2. Should we offer a choice to the end user? This might introduce a lot of complexity.
3. If we *do not* delete such directories, should they still be tracked as created files by astrality?

Astrality should never delete content that it has not created, so we should take extra care here. As a first pass at the problem, we could only delete created directories if they are empty after all other cleanup is done.

**Comment by KeithScheiwiller** [comment]
@JakobGM Awesome, thank you so much for the quick turnaround!
No feedback from me, looks great!
