### ISSUE TITLE
Allow enabling single modules from the CLI

### ISSUE THREAD

**Issue by JakobGM** [JakobGM/astrality#14]
You should be able to run ``astrality --module MODULE1 MODULE2 MODULE3`` in order to quickly run specific module(s). That way you could check out some other astrality module by running ``astrality -m github::jakobgm/polybar`` in order to effortlessly try modules created by others.

It should not be too hard to implement. You would need to 

- [x] Add another ``argparse`` argument [here](https://github.com/JakobGM/astrality/blob/8fabae6c3215c5f0fd1e232236f48b1194549f8a/bin/astrality#L36).
- [x] [Pass the new argument](https://github.com/JakobGM/astrality/blob/8fabae6c3215c5f0fd1e232236f48b1194549f8a/bin/astrality#L53) to ``astrality.astrality.main``.
- [x] Add a [new parameter](https://github.com/JakobGM/astrality/blob/8fabae6c3215c5f0fd1e232236f48b1194549f8a/astrality/astrality.py#L19) to ``main``. It could have default value ``enabled_modules: str = ''``.
- [x] Modify the config object [here](https://github.com/JakobGM/astrality/blob/8fabae6c3215c5f0fd1e232236f48b1194549f8a/astrality/astrality.py#L78). Something along the lines of:
  ```python
  if enabled_modules:
    config['config/module']['enabled_modules'] = [
      {'name': enabled_module}
      for enabled_module
      in enabled_modules.split(' ')
    ]
  ```
- [x] Perhaps add a new parameter ``kill_processes: bool = True`` to ``main`` and set it to ``False`` when using the ``--modules`` option? This way, you could run specific modules on top of the already running instance of astrality.

The testing strategy could be to unit-test ``astrality.astrality.main`` while monkey patching the return value of ``os.environ['ASTRALITY_CONFIG_HOME']`` to some configuration directory which contains a module with some easily testable side-effect. Perhaps ``run: shell: 'touch touched.tmp'``? Monkey patching ``os.environ`` is explained [here](https://stackoverflow.com/a/30918483).

Is this something you would like to implement, @sshashank124?

**Comment by sshashank124** [comment]
So the `astrality --modules` process should run independently of a potentially already running main astrality process? Yes I can work on this

**Comment by JakobGM** [comment]
Yes, I think that makes the most sense. Let's say I have already Astrality running in the background. Then I would like to test out a new module. I think that should not kill my already existing background process.

**Comment by JakobGM** [comment]
I did some refactoring recently which made this change quite easy, so I took the liberty to implement the feature myself ;)
