### ISSUE TITLE
Allow chmod-like template permission bits

### ISSUE THREAD

**Issue by JakobGM** [JakobGM/astrality#4]
The ``permission`` option for the template ``compile`` action should allow ``chmod``-like permission specifications, e.g. ``u+x``. See the discussion in #2.

One drawback by this approach is that it would require sub-shelling out to ``chmod``, as ``os.chmod`` only supports literal byte assignments to ``Path.stat().st_mode``, but I consider this an acceptable performance hit. We probably do not want to reimplement UNIX-``chmod`` from scratch in python, as that would be ripe for bugs.

Sub-shelling should be done throug the ``subprocess.Popen`` wrapper located defined in [``astrality.utils.run_shell``](https://github.com/JakobGM/astrality/blob/v0.6/astrality/utils.py#L12).

This should be considered blocked by #3.

**Comment by sshashank124** [comment]
I think anyone, myself included, who is looking for the versatility of both the `'u+x'` and `'755'` approach for specifying the permissions wouldn't mind it being implemented through subshelling.

Also, do we necessarily want to allow the user to specify either `0o755` or `'755'` in the configuration? I personally think it's always just easier to specify `'755'` and that way there isn't the potential confusions between int (octal vs dec) and string for the user to worry about.

Either way, once #3 is resolved, I would like to be assigned this issue

**Comment by JakobGM** [comment]
I totally agree, I didn't really think it through properly. Only string permissions should be allowed. Let's remove support for numeric ``permission`` values, and only allow strings.

Let's always subshell out, and mention in the documentation that the ``permission`` option is passed to the ``chmod`` UNIX-command. That way, the end-user knows exactly what it entails, and the documentation becomes more readable. The warning in the documentation can therefore also be removed.

By the way, you can use ``fallback=False`` in [``astrality.utils.run_shell``](https://github.com/JakobGM/astrality/blob/master/astrality/utils.py#L15) to check if the sub-shelling was successfull or not by comparing the result with ``False``, i.e.:
```python
result = run_shell(..., fallback=False)
if result is False:
    # logg error or some error handling
```

**Comment by sshashank124** [comment]
Sounds good. Just to be super clear, when you say "always subshell out", are you also including the case of default permissions where the permission bits are copied or will that case still just use `path.chmod(mode)`?

**Comment by JakobGM** [comment]
The default behaviour, in the absence of a ``permissions`` argument, should still use ``path.chmod(mode)``, I agree. 

So I should have said "always subshell out in the case of a specified permission" instead.

**Comment by sshashank124** [comment]
As mentioned in #3, the new updated flow is that the default permissions are always copied and the `permissions` value provided in the configuration files is applied _on top_ of the default

**Comment by JakobGM** [comment]
If you are going to write a unit test for a function in the compiler module, I would write it in the latter one. I wrote some integration tests, i.e. permissions as part of an enture module, in the former. But the test module hierarchy might be a bit confusing and unordered!
