### ISSUE TITLE
Add instructions for how to contribute

### ISSUE THREAD

**Issue by JakobGM** [JakobGM/astrality#5]
Astrality should document how to contribute, if anyone wants to help.

It should probably include the following:
- [x] How to clone the repository.
- [x] Create a virtual environment for ``python3.6``.
- [x] How to install the dependencies.
- [x] Contribute code in the form of pull requests.
- [x] Highly encourouge 100% test coverage of any new code paths, but make it clear that untested code is better than no code.
- [x] Non-test code shoud be type annotated.
- [x] Add yourself to ``CONTRIBUTORS.rst``.

For now it goes something along the lines of (assuming the use of virtualenvwrapper):
```bash
git clone https://github.com/jakobgm/astrality
cd astrality
mkproject -p python3.6 -a $PWD -r requirements.txt astrality
pytest --runslow
```

Additional nice-to-haves:
- [x] The ``pytest --runslow`` should probably also be documented.
- [x] Some tests depends on ``feh`` and ``conky`` being installed on the system.
- [x] Use ``pytest-watchdog`` while developing.
- [x] Explain that pull requests are automatically tested.
- [x] Link to contributing guidelines from the documentation.
- [x] How to compile the documentation locally and view it in the browser.
- [x] How to set the debug level, and how to log in the first place.

**Comment by sshashank124** [comment]
Once I can maybe get #3 and #4 completed or under way and I have more experience with the workflow, I could contribute to this. There were a couple little issues I ran into trying to setup or run the project that I could document. Although, I don't think I understand enough yet to be able to make a comprehensive guide.

**Comment by JakobGM** [comment]
That makes sense.

I can make a draft for the contributing guidelines, and when I commit it, you could perhaps check if I missed some of the points that tripped you up? I probably have some blindspots regarding unobvious stuff.

**Comment by JakobGM** [comment]
Do you by chance now where such a document should be placed? I usually see ``CONTRIBUTING.md`` in other projects, but it seems to often contain non-technical details such as the [contributor covenant](http://contributor-covenant.org/). Where should I put the more technical instructions?

**Comment by sshashank124** [comment]
Yeah I could look at the guidelines and add my POV.

I don't there's a hard and fast rule for where to place the guidelines. I think `CONTRIBUTING.md` should work just fine. I've also seen some projects store it in the Wiki.

**Comment by JakobGM** [comment]
I have now written a first draft for contributing guidelines in #7. I would appreciate any feedback!

One good thing; ``feh`` and ``conky`` are apparently not required in order to pass ``pytest --runslow`` as those modules now utilize the ``requires`` option for modules.

**Comment by sshashank124** [comment]
Can we close this?
