### ISSUE TITLE
Implement a linter as part of the test suite

### ISSUE THREAD

**Issue by JakobGM** [JakobGM/astrality#8]
I'm a big fan of tool-based formatting, offloading the task of formatting code to automated tools. 

Additionally, the code style section in ``CONTRIBUTING.rst`` should be codified in the form of some linter's configuration file.

In order to make this as automated as possible, we should pursue the following goals:
- [x] Make all existing code compliant with some set of lint rules. ``PEP 8`` should be a good starting point. We can always add additional rules at some later point in time.
- [x] Fix linting errors in the test suite.
- [x] Decide on which linter(s) to use. [``flake8``](http://flake8.pycqa.org/en/latest/) seems to be a good choice here, but more research needs to be done.
- [x] Research good tools for automatic code formating. [``YAPF``](https://github.com/google/yapf) seems interesting.
- [x] Integrate an automatic code formatter as a pre-commit hook.
- [x] Integrate linter into Travis-CI.
- [x] Integrate the linter(s) into the pytest test suite.

I have already started the work of complying to the PEP 8 standard everywhere in the code base.

**Comment by JakobGM** [comment]
d81a8002b8fbba87c69fe08276185f618c150fc7 to 87de731febd65fe1ec418405dd1d1fc23e432b0f has now fixed all ``flake8`` linting errors in application code.

The huge task of passing linting requirements in test code remains. I think we should ignore several linting rules in testing code, such as docstring requirement, and perhaps increase the allowable line-width to 120 character for the test submodule?

**Comment by JakobGM** [comment]
I have looked at using the pytest plugin ``pytest-flake8``, but it seems that it breaks ``--runslow`` by skipping all slow tests even when ``pytest`` is passed ``--runslow``. I will check if this is case for a dummy repository, and submit an issue to ``tholo/pytest-flake8
`` if so.

**Comment by sshashank124** [comment]
Maybe we can just go with the Travis solution for now and put it on ourselves to keep linting when developing.

In the meantime, we can keep exploring options for auto lint-checking and we could always fallback onto pytest-flake8 if no alternative is found

**Comment by JakobGM** [comment]
Ok, I will add it to the Travis-CI configuration now.

**Comment by sshashank124** [comment]
> Additionally, the code style section in CONTRIBUTING.rst should be codified in the form of some linter's configuration file.

[`flake8-commas`](https://github.com/PyCQA/flake8-commas) for trailing commas
[`flake8-quotes`](https://github.com/zheller/flake8-quotes) for single quote string literals
Could not find one for forced keyword arguments although it seems possible through the core python language as explained [here](https://stackoverflow.com/questions/2965271/forced-naming-of-parameters-in-python)

**Comment by JakobGM** [comment]
I think I might have been wrong when I said that forced keyword arguments is the correct thing to do, it is too much dependent of the context, function name, and arity. Perhaps I should remove that part of the style guide?

And apropo of nothing, at the momemt, there are lots of places in the code base where we have code like this:

```python
def foobar(
    a,
    b,
    c
):
    pass
```

But YAPF default behaviour is to double indent such arguments (because they think that is more legible, since it distinguishes arguments from the function body) like this:

```python
def foobar(
        a,
        b,
        c
):
    pass
```

At the moment, it is not possible to configure YAPF to format code like the way we have done it so far. Take a look at this issue: google/yapf/issues/460

Do you think we should use the double indentation style, or should we disable YAPF from touching any function arguments? I'm really ased to single indentation, but style should follow convention, and it seems that I'm in the wrong here...

If we decide to double indent, it should not be much work at all, since I can just run YAPF on each file and commit those changes.

**Comment by sshashank124** [comment]
I prefer single indenting too but I think it would just be simpler to use the double indentation style and have one less thing to worry about. It'd be nice to introduce exceptions to linting/formatting rules as seldomly as possible
